%YAML:1.0

#==================== Camera Model (CAVE / cam0) ====================
Camera.type: "PinHole"

# 内参 (来自官方 intrinsics)
Camera.fx: 1156.5188534683703
Camera.fy: 1156.5772666173266
Camera.cx: 763.2083316463371
Camera.cy: 617.2779853849335

# radtan 畸变：k1, k2, p1, p2  （注意 p1/p2，不能再写 k3/k4）
Camera.k1: -0.17473019446863114
Camera.k2:  0.10643290428040156
Camera.p1:  0.005210777878907861
Camera.p2: -0.00028664918860079295

# 分辨率
Camera.width: 1600
Camera.height: 1200

# 帧率（如果不确定，可以先 20.0，或者查一下 bag，问题不大）
Camera.fps: 20.0
Camera.RGB: true 


#==================== ORB Extractor ====================
# 水下/低纹理：适度多特征 + 降低 FAST 初阈
ORBextractor.nFeatures: 900
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 12
ORBextractor.minThFAST: 7


#==================== Viewer ====================
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
# ==================== UW-Fusion（从 YAML 读取） ====================
# Enhance-Default（默认增强）
uwfusion.enable: 0
uwfusion.levels: 4
uwfusion.scb_percent: 0.6
uwfusion.bilateral_d: 3
uwfusion.bilateral_sigma_color: 4.0
uwfusion.bilateral_sigma_space: 3.5
uwfusion.clahe_clip: 1.4
uwfusion.clahe_tile: 8
uwfusion.exposed_avg: 0.5
uwfusion.exposed_sigma: 0.25

# ==================== InfoSelector（点号扁平写法） ====================
InfoSelector.Enable: 0
InfoSelector.TopK: 95
InfoSelector.UseUniform: 0
InfoSelector.w_uniform: 0.12
InfoSelector.MinPxDist: 7

InfoSelector.LambdaInit: 1.0e-3


# =============== InfoKF (keyframe gating) ===============
InfoKF.Use: 1             # 打开信息论关键帧门控
InfoKF.AllowBitsDrop: 2.2 # T0：信息变化容忍度（主参数）

# 自适应强度（轻微即可）
InfoKF.Dyn.Alpha: 0.25       # 影响 Teff 的幅度不要太大
InfoKF.Dyn.Beta:  0.0       # 暂时不用，可以留着以后扩展

# 自适应阈值上下界（建议）
InfoKF.Dyn.TauMin: 0.1
InfoKF.Dyn.TauMax: 5.0

# 累计量 & 帧距兜底
InfoKF.Cum.Decay: 0.95
InfoKF.Cum.Thr:   0.5
InfoKF.MaxFramesForce: 300  # 目前你说先不启用，可以先设很大

