%YAML:1.0

File.version: "1.0"

Camera.type: "PinHole"

Camera1.fx: 655.0
Camera1.fy: 655.0
Camera1.cx: 306.0
Camera1.cy: 256.0

Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0

Camera.width: 612
Camera.height: 512
Camera.fps: 20
Camera.RGB: 1

IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [ -0.0165093370, -0.0174868879, -0.9997107834, -0.211687435,
           -0.0105946453,  0.9997939789, -0.0173133820, -0.097259169,
            0.9998075791,  0.0103057487, -0.0166912031, -0.056238089,
            0.0,           0.0,           0.0,           1.0 ]

IMU.NoiseGyro: 1.0e-4
IMU.NoiseAcc: 2.3e-4
IMU.GyroWalk: 3.6e-6
IMU.AccWalk: 6.7e-6
IMU.Frequency: 333.0

timeshift_cam_imu: 0.0
IMU.InsertKFsWhenLost: 1
IMU.ResetActiveMapBeforeInit: 0
IMU.RecentlyLostTime: 10.0
IMU.MinInitTrackedPoints: 30
IMU.MinTrackLocalMapInliersBeforeInit: 25


ORBextractor.nFeatures: 1600
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 10
ORBextractor.minThFAST: 5

Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0

uwfusion.enable: 1
uwfusion.levels: 4
uwfusion.scb_percent: 0.6
uwfusion.bilateral_d: 3
uwfusion.bilateral_sigma_color: 4.0
uwfusion.bilateral_sigma_space: 3.5
uwfusion.clahe_clip: 1.4
uwfusion.clahe_tile: 8
uwfusion.exposed_avg: 0.5
uwfusion.exposed_sigma: 0.25

InfoSelector.Enable: 1
InfoSelector.TopK: 220
InfoSelector.UseUniform: 1
InfoSelector.w_uniform: 0.12
InfoSelector.MinPxDist: 7
InfoSelector.LambdaInit: 1.0e-3

InfoKF.Use: 1
InfoKF.AllowBitsDrop: 1.0
InfoKF.Dyn.Alpha: 0.25
InfoKF.Dyn.Beta: 0.0
InfoKF.Dyn.TauMin: 0.1
InfoKF.Dyn.TauMax: 5.0
InfoKF.Cum.Decay: 0.95
InfoKF.Cum.Thr: 0.5
InfoKF.MaxFramesForce: 300
