#!/usr/bin/env bash
set -euo pipefail

# Shared AIDVO smoke-test driver. Dataset wrappers only provide paths and launch files.
WS="${WS:-$HOME/catkin_ws}"
ROS_HOME_DIR="${ROS_HOME:-$HOME/.ros}"
AIDVO_MODE="${AIDVO_MODE:-rule}"       # off | fixed | rule
BAG_RATE="${BAG_RATE:-1.0}"
BAG_DURATION="${BAG_DURATION:-0}"      # 0 means play the full bag
RUN_ALL_BAGS="${RUN_ALL_BAGS:-0}"
STARTUP_WAIT="${STARTUP_WAIT:-8}"
VOC_FILE="${VOC_FILE:-$WS/src/orb_slam3_ros/orb_slam3/Vocabulary/ORBvoc.txt.bin}"

require_command() {
  command -v "$1" >/dev/null 2>&1 || { echo "[ERROR] Missing command: $1"; return 1; }
}

wait_for_orb_slam3_node() {
  local launch_pid="$1"
  local launch_log="$2"
  local deadline=$((SECONDS + STARTUP_WAIT))

  while [ "${SECONDS}" -lt "${deadline}" ]; do
    if ! kill -0 "${launch_pid}" >/dev/null 2>&1; then
      echo "[ERROR] roslaunch exited during startup. See ${launch_log}"
      tail -n 80 "${launch_log}" || true
      return 1
    fi
    if rosnode list 2>/dev/null | grep -q '^/orb_slam3$'; then
      return 0
    fi
    sleep 1
  done

  echo "[ERROR] /orb_slam3 did not appear within ${STARTUP_WAIT}s. Bag playback is skipped."
  echo "[ERROR] See ${launch_log}"
  tail -n 80 "${launch_log}" || true
  return 1
}

wait_for_launch_log_pattern() {
  local launch_pid="$1"
  local launch_log="$2"
  local pattern="$3"
  local deadline=$((SECONDS + STARTUP_WAIT))

  while [ "${SECONDS}" -lt "${deadline}" ]; do
    if grep -q "${pattern}" "${launch_log}"; then
      return 0
    fi
    if ! kill -0 "${launch_pid}" >/dev/null 2>&1; then
      echo "[ERROR] roslaunch exited before expected log appeared: ${pattern}"
      tail -n 80 "${launch_log}" || true
      return 1
    fi
    sleep 1
  done

  echo "[ERROR] Missing expected startup log: ${pattern}"
  echo "[ERROR] See ${launch_log}"
  tail -n 80 "${launch_log}" || true
  return 1
}

prepare_aidvo_config() {
  local base_config="$1"
  local output_config="$2"
  local adaptive_log="$3"
  local enable=1
  local policy="RuleBased"

  case "${AIDVO_MODE}" in
    off) enable=0; policy="Fixed" ;;
    fixed) enable=1; policy="Fixed" ;;
    rule) enable=1; policy="RuleBased" ;;
    *) echo "[ERROR] AIDVO_MODE must be off, fixed, or rule"; return 1 ;;
  esac

  awk '
    !/^[[:space:]]*(EnableAdaptiveIDVO|AdaptivePolicyType|MinKappaTop|MaxKappaTop|MinTau0|MaxTau0|TrackingTimeBudget|SmoothFactor|EnableAdaptiveLogging|AdaptiveLogPath|Adaptive\.LowLogDetH|Adaptive\.PoorConditionNumber|Adaptive\.LowInlierRatio|Adaptive\.BlurThreshold)[[:space:]]*:/
  ' "${base_config}" > "${output_config}"

  cat >> "${output_config}" <<EOF

# Generated by Parameters_test/aidvo_smoke_common.sh
EnableAdaptiveIDVO: ${enable}
AdaptivePolicyType: "${policy}"
MinKappaTop: ${MIN_KAPPA_TOP:-60}
MaxKappaTop: ${MAX_KAPPA_TOP:-180}
MinTau0: ${MIN_TAU0:-0.1}
MaxTau0: ${MAX_TAU0:-5.0}
TrackingTimeBudget: ${TRACKING_TIME_BUDGET:-30.0}
SmoothFactor: ${SMOOTH_FACTOR:-0.8}
EnableAdaptiveLogging: ${ENABLE_ADAPTIVE_LOGGING:-1}
AdaptiveLogPath: "${adaptive_log}"
EOF
}

run_aidvo_bag() {
  local sensor_mode="$1"
  local dataset="$2"
  local launch_name="$3"
  local base_config="$4"
  local bag_file="$5"
  local results_root="$6"
  local bag_name run_dir generated_config adaptive_log launch_log launch_pid

  bag_name="$(basename "${bag_file}" .bag)"
  run_dir="${results_root}/${sensor_mode}/${dataset}/${AIDVO_MODE}/${bag_name}"
  mkdir -p "${run_dir}"
  generated_config="${run_dir}/settings_${AIDVO_MODE}.yaml"
  adaptive_log="${run_dir}/adaptive_frames.csv"
  launch_log="${run_dir}/roslaunch.log"
  rm -f "${adaptive_log}"
  prepare_aidvo_config "${base_config}" "${generated_config}" "${adaptive_log}"

  echo "[INFO] mode=${sensor_mode} dataset=${dataset} aidvo=${AIDVO_MODE}"
  echo "[INFO] bag=${bag_file}"
  echo "[INFO] config=${generated_config}"

  roslaunch orb_slam3_ros "${launch_name}" \
    voc_file:="${VOC_FILE}" settings_file:="${generated_config}" \
    >"${launch_log}" 2>&1 &
  launch_pid=$!

  cleanup_aidvo_run() {
    rosnode kill /orb_slam3 >/dev/null 2>&1 || true
    kill "${launch_pid}" >/dev/null 2>&1 || true
    wait "${launch_pid}" 2>/dev/null || true
  }
  trap cleanup_aidvo_run EXIT INT TERM

  wait_for_orb_slam3_node "${launch_pid}" "${launch_log}"

  wait_for_launch_log_pattern "${launch_pid}" "${launch_log}" "Adaptive IDVO params loaded"

  local play_args=(play "${bag_file}" --clock -r "${BAG_RATE}")
  if [[ "${BAG_DURATION}" != "0" ]]; then
    play_args+=(--duration "${BAG_DURATION}")
  fi
  rosbag "${play_args[@]}"
  sleep 3

  if rosservice info /orb_slam3/save_traj >/dev/null 2>&1; then
    rosservice call /orb_slam3/save_traj "aidvo_${sensor_mode}_${dataset}_${bag_name}_${AIDVO_MODE}" || true
  fi

  cleanup_aidvo_run
  trap - EXIT INT TERM

  grep -q "Adaptive IDVO params loaded" "${launch_log}" || {
    echo "[ERROR] AIDVO configuration was not loaded. See ${launch_log}"
    return 1
  }
  local expected_switch="YES"
  [[ "${AIDVO_MODE}" == "off" ]] && expected_switch="NO"
  grep -q "EnableAdaptiveIDVO: ${expected_switch}" "${launch_log}" || {
    echo "[ERROR] AIDVO switch does not match AIDVO_MODE=${AIDVO_MODE}"
    return 1
  }

  if [[ "${ENABLE_ADAPTIVE_LOGGING:-1}" == "1" && ! -s "${adaptive_log}" ]]; then
    echo "[WARN] Adaptive log is empty. For inertial modes, ensure the bag reaches IMU initialization."
  else
    echo "[PASS] adaptive log: ${adaptive_log}"
  fi
  echo "[PASS] launch log: ${launch_log}"
}

run_aidvo_dataset() {
  local sensor_mode="$1"
  local dataset="$2"
  local launch_name="$3"
  local base_config="$4"
  local bag_dir="$5"
  local bag_pattern="${6:-*.bag}"
  local results_root="${7:-$bag_dir/../aidvo_results}"
  local bags=()

  [[ -f "${VOC_FILE}" ]] || { echo "[ERROR] Vocabulary not found: ${VOC_FILE}"; return 1; }
  [[ -f "${base_config}" ]] || { echo "[ERROR] Config not found: ${base_config}"; return 1; }
  [[ -d "${bag_dir}" ]] || { echo "[ERROR] Bag directory not found: ${bag_dir}"; return 1; }
  [[ -f "${WS}/devel/setup.bash" ]] || { echo "[ERROR] Build workspace first: ${WS}/devel/setup.bash"; return 1; }
  # shellcheck disable=SC1090
  source "${WS}/devel/setup.bash"
  require_command roslaunch
  require_command rosbag
  require_command rosnode

  if [[ -n "${BAG_FILE:-}" ]]; then
    bags=("${BAG_FILE}")
  else
    mapfile -t bags < <(find "${bag_dir}" -maxdepth 1 -type f -name "${bag_pattern}" | sort)
  fi
  [[ ${#bags[@]} -gt 0 ]] || { echo "[ERROR] No bags matching ${bag_dir}/${bag_pattern}"; return 1; }

  if [[ "${RUN_ALL_BAGS}" != "1" ]]; then
    bags=("${bags[0]}")
  fi
  for bag in "${bags[@]}"; do
    run_aidvo_bag "${sensor_mode}" "${dataset}" "${launch_name}" \
      "${base_config}" "${bag}" "${results_root}"
  done
}
